spring.application.name=notificaciones-service

server.port=${PORT:8087}

# Gmail SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hospitallabendicion6@gmail.com
spring.mail.password=gzyl oqco cxgp hjpg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
 


spring.mail.properties.mail.smtp.starttls.required=true
