spring.application.name=historial-medico-service

server.port=${PORT:8088}

spring.datasource.url=jdbc:postgresql://localhost:5432/historial_db
spring.datasource.username=postgres
spring.datasource.password=123456k

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=clave_super_segura_12345678901234567890
